[2025-04-28T22:00:38.223+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-28T22:00:32+00:00 [queued]>
[2025-04-28T22:00:38.235+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-28T22:00:32+00:00 [queued]>
[2025-04-28T22:00:38.235+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-28T22:00:38.254+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-28 22:00:32+00:00
[2025-04-28T22:00:38.261+0000] {standard_task_runner.py:60} INFO - Started process 15897 to run task
[2025-04-28T22:00:38.266+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-28T22:00:32+00:00', '--job-id', '7064', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmpjnoj3g32']
[2025-04-28T22:00:38.268+0000] {standard_task_runner.py:88} INFO - Job 7064: Subtask load_mysql_data
[2025-04-28T22:00:38.338+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-28T22:00:32+00:00 [running]> on host 9c429c713f45
[2025-04-28T22:00:38.469+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T22:00:32+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T22:00:32+00:00'
[2025-04-28T22:00:38.470+0000] {mymind_etl_dag.py:284} INFO - Iniciando carga a MySQL: 5 usuarios, 9 transcripciones.
[2025-04-28T22:00:38.471+0000] {mymind_etl_dag.py:295} INFO - Cargando 5 usuarios en la tabla users...
[2025-04-28T22:00:38.480+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-28T22:00:38.492+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into users
[2025-04-28T22:00:38.492+0000] {mymind_etl_dag.py:303} INFO - Usuarios cargados exitosamente.
[2025-04-28T22:00:38.492+0000] {mymind_etl_dag.py:322} INFO - Cargando 9 transcripciones en la tabla transcriptions...
[2025-04-28T22:00:38.500+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-28T22:00:38.507+0000] {sql.py:547} INFO - Done loading. Loaded a total of 9 rows into transcriptions
[2025-04-28T22:00:38.507+0000] {mymind_etl_dag.py:330} INFO - Transcripciones cargadas exitosamente.
[2025-04-28T22:00:38.508+0000] {mymind_etl_dag.py:335} INFO - Carga a MySQL completada con Ã©xito.
[2025-04-28T22:00:38.508+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-28T22:00:38.518+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250428T220032, start_date=20250428T220038, end_date=20250428T220038
[2025-04-28T22:00:38.560+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T22:00:38.578+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
