[2025-04-29T00:00:11.736+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T00:00:06+00:00 [queued]>
[2025-04-29T00:00:11.747+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T00:00:06+00:00 [queued]>
[2025-04-29T00:00:11.748+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-29T00:00:11.765+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-29 00:00:06+00:00
[2025-04-29T00:00:11.772+0000] {standard_task_runner.py:60} INFO - Started process 21998 to run task
[2025-04-29T00:00:11.776+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-29T00:00:06+00:00', '--job-id', '8065', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmpyeqbl1mr']
[2025-04-29T00:00:11.778+0000] {standard_task_runner.py:88} INFO - Job 8065: Subtask load_mysql_data
[2025-04-29T00:00:11.841+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T00:00:06+00:00 [running]> on host 9c429c713f45
[2025-04-29T00:00:11.958+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T00:00:06+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-29T00:00:06+00:00'
[2025-04-29T00:00:11.959+0000] {mymind_etl_dag.py:284} INFO - Iniciando carga a MySQL: 5 usuarios, 9 transcripciones.
[2025-04-29T00:00:11.960+0000] {mymind_etl_dag.py:295} INFO - Cargando 5 usuarios en la tabla users...
[2025-04-29T00:00:11.971+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T00:00:11.987+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into users
[2025-04-29T00:00:11.988+0000] {mymind_etl_dag.py:303} INFO - Usuarios cargados exitosamente.
[2025-04-29T00:00:11.988+0000] {mymind_etl_dag.py:322} INFO - Cargando 9 transcripciones en la tabla transcriptions...
[2025-04-29T00:00:11.995+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T00:00:12.002+0000] {sql.py:547} INFO - Done loading. Loaded a total of 9 rows into transcriptions
[2025-04-29T00:00:12.003+0000] {mymind_etl_dag.py:330} INFO - Transcripciones cargadas exitosamente.
[2025-04-29T00:00:12.003+0000] {mymind_etl_dag.py:335} INFO - Carga a MySQL completada con Ã©xito.
[2025-04-29T00:00:12.003+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-29T00:00:12.015+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250429T000006, start_date=20250429T000011, end_date=20250429T000012
[2025-04-29T00:00:12.068+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-29T00:00:12.086+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
