[2025-04-25T11:15:04.314+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-25T11:10:00+00:00 [queued]>
[2025-04-25T11:15:04.322+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-25T11:10:00+00:00 [queued]>
[2025-04-25T11:15:04.322+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-25T11:15:04.336+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-25 11:10:00+00:00
[2025-04-25T11:15:04.341+0000] {standard_task_runner.py:60} INFO - Started process 47300 to run task
[2025-04-25T11:15:04.344+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-25T11:10:00+00:00', '--job-id', '1640', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmplado0jo3']
[2025-04-25T11:15:04.345+0000] {standard_task_runner.py:88} INFO - Job 1640: Subtask load_mysql_data
[2025-04-25T11:15:04.402+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-25T11:10:00+00:00 [running]> on host 64c6827685b2
[2025-04-25T11:15:04.521+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T11:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-25T11:10:00+00:00'
[2025-04-25T11:15:04.522+0000] {mymind_etl_dag.py:284} INFO - Iniciando carga a MySQL: 3 usuarios, 5 transcripciones.
[2025-04-25T11:15:04.522+0000] {mymind_etl_dag.py:295} INFO - Cargando 3 usuarios en la tabla users...
[2025-04-25T11:15:04.533+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-25T11:15:04.549+0000] {sql.py:547} INFO - Done loading. Loaded a total of 3 rows into users
[2025-04-25T11:15:04.549+0000] {mymind_etl_dag.py:303} INFO - Usuarios cargados exitosamente.
[2025-04-25T11:15:04.549+0000] {mymind_etl_dag.py:322} INFO - Cargando 5 transcripciones en la tabla transcriptions...
[2025-04-25T11:15:04.557+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-25T11:15:04.564+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into transcriptions
[2025-04-25T11:15:04.564+0000] {mymind_etl_dag.py:330} INFO - Transcripciones cargadas exitosamente.
[2025-04-25T11:15:04.565+0000] {mymind_etl_dag.py:335} INFO - Carga a MySQL completada con Ã©xito.
[2025-04-25T11:15:04.565+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-25T11:15:04.576+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250425T111000, start_date=20250425T111504, end_date=20250425T111504
[2025-04-25T11:15:04.596+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-25T11:15:04.627+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
