[2025-04-29T20:00:09.747+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T20:00:04+00:00 [queued]>
[2025-04-29T20:00:09.756+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T20:00:04+00:00 [queued]>
[2025-04-29T20:00:09.756+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-29T20:00:09.771+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-29 20:00:04+00:00
[2025-04-29T20:00:09.778+0000] {standard_task_runner.py:60} INFO - Started process 328 to run task
[2025-04-29T20:00:09.781+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-29T20:00:04+00:00', '--job-id', '18801', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmpeqj7ng58']
[2025-04-29T20:00:09.782+0000] {standard_task_runner.py:88} INFO - Job 18801: Subtask load_mysql_data
[2025-04-29T20:00:09.832+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T20:00:04+00:00 [running]> on host d10170178d9f
[2025-04-29T20:00:09.936+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T20:00:04+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-29T20:00:04+00:00'
[2025-04-29T20:00:09.937+0000] {mymind_etl_dag.py:284} INFO - Iniciando carga a MySQL: 5 usuarios, 9 transcripciones.
[2025-04-29T20:00:09.938+0000] {mymind_etl_dag.py:295} INFO - Cargando 5 usuarios en la tabla users...
[2025-04-29T20:00:09.947+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T20:00:09.958+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into users
[2025-04-29T20:00:09.958+0000] {mymind_etl_dag.py:303} INFO - Usuarios cargados exitosamente.
[2025-04-29T20:00:09.958+0000] {mymind_etl_dag.py:322} INFO - Cargando 9 transcripciones en la tabla transcriptions...
[2025-04-29T20:00:09.963+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T20:00:09.968+0000] {sql.py:547} INFO - Done loading. Loaded a total of 9 rows into transcriptions
[2025-04-29T20:00:09.969+0000] {mymind_etl_dag.py:330} INFO - Transcripciones cargadas exitosamente.
[2025-04-29T20:00:09.969+0000] {mymind_etl_dag.py:335} INFO - Carga a MySQL completada con Ã©xito.
[2025-04-29T20:00:09.969+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-29T20:00:09.979+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250429T200004, start_date=20250429T200009, end_date=20250429T200009
[2025-04-29T20:00:10.034+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-29T20:00:10.052+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
