[2025-04-29T10:40:39.920+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T10:40:34+00:00 [queued]>
[2025-04-29T10:40:39.931+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T10:40:34+00:00 [queued]>
[2025-04-29T10:40:39.932+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-29T10:40:39.945+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-29 10:40:34+00:00
[2025-04-29T10:40:39.951+0000] {standard_task_runner.py:60} INFO - Started process 56640 to run task
[2025-04-29T10:40:39.956+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-29T10:40:34+00:00', '--job-id', '13868', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmppqzhhgtp']
[2025-04-29T10:40:39.957+0000] {standard_task_runner.py:88} INFO - Job 13868: Subtask load_mysql_data
[2025-04-29T10:40:40.011+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T10:40:34+00:00 [running]> on host 9c429c713f45
[2025-04-29T10:40:40.113+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T10:40:34+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-29T10:40:34+00:00'
[2025-04-29T10:40:40.114+0000] {mymind_etl_dag.py:284} INFO - Iniciando carga a MySQL: 5 usuarios, 9 transcripciones.
[2025-04-29T10:40:40.115+0000] {mymind_etl_dag.py:295} INFO - Cargando 5 usuarios en la tabla users...
[2025-04-29T10:40:40.123+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T10:40:40.133+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into users
[2025-04-29T10:40:40.134+0000] {mymind_etl_dag.py:303} INFO - Usuarios cargados exitosamente.
[2025-04-29T10:40:40.134+0000] {mymind_etl_dag.py:322} INFO - Cargando 9 transcripciones en la tabla transcriptions...
[2025-04-29T10:40:40.140+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T10:40:40.145+0000] {sql.py:547} INFO - Done loading. Loaded a total of 9 rows into transcriptions
[2025-04-29T10:40:40.145+0000] {mymind_etl_dag.py:330} INFO - Transcripciones cargadas exitosamente.
[2025-04-29T10:40:40.146+0000] {mymind_etl_dag.py:335} INFO - Carga a MySQL completada con Ã©xito.
[2025-04-29T10:40:40.146+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-29T10:40:40.154+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250429T104034, start_date=20250429T104039, end_date=20250429T104040
[2025-04-29T10:40:40.167+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-29T10:40:40.184+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
