[2025-04-17T00:00:05.631+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-16T00:00:00+00:00 [queued]>
[2025-04-17T00:00:05.640+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-16T00:00:00+00:00 [queued]>
[2025-04-17T00:00:05.640+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-17T00:00:05.655+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-16 00:00:00+00:00
[2025-04-17T00:00:05.660+0000] {standard_task_runner.py:60} INFO - Started process 25208 to run task
[2025-04-17T00:00:05.663+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-16T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmpd1s8h2yy']
[2025-04-17T00:00:05.664+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask load_mysql_data
[2025-04-17T00:00:05.721+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-16T00:00:00+00:00 [running]> on host 64c6827685b2
[2025-04-17T00:00:05.845+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-16T00:00:00+00:00'
[2025-04-17T00:00:05.846+0000] {logging_mixin.py:188} INFO - Iniciando carga a MySQL: 4 usuarios, 8 transcripciones.
[2025-04-17T00:00:05.847+0000] {logging_mixin.py:188} INFO - Cargando 4 usuarios en la tabla users...
[2025-04-17T00:00:05.858+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-17T00:00:05.877+0000] {sql.py:547} INFO - Done loading. Loaded a total of 4 rows into users
[2025-04-17T00:00:05.877+0000] {logging_mixin.py:188} INFO - Usuarios cargados.
[2025-04-17T00:00:05.877+0000] {logging_mixin.py:188} INFO - Cargando 8 transcripciones en la tabla transcriptions...
[2025-04-17T00:00:05.886+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-17T00:00:05.893+0000] {sql.py:547} INFO - Done loading. Loaded a total of 8 rows into transcriptions
[2025-04-17T00:00:05.894+0000] {logging_mixin.py:188} INFO - Transcripciones cargadas.
[2025-04-17T00:00:05.894+0000] {logging_mixin.py:188} INFO - Carga a MySQL completada.
[2025-04-17T00:00:05.894+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-17T00:00:05.907+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250416T000000, start_date=20250417T000005, end_date=20250417T000005
[2025-04-17T00:00:05.955+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-17T00:00:05.984+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
