[2025-05-01T22:40:57.817+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-05-01T22:40:47+00:00 [queued]>
[2025-05-01T22:40:57.842+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-05-01T22:40:47+00:00 [queued]>
[2025-05-01T22:40:57.843+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-01T22:40:57.876+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-05-01 22:40:47+00:00
[2025-05-01T22:40:57.900+0000] {standard_task_runner.py:60} INFO - Started process 341 to run task
[2025-05-01T22:40:57.908+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-05-01T22:40:47+00:00', '--job-id', '20633', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmptru189h_']
[2025-05-01T22:40:57.910+0000] {standard_task_runner.py:88} INFO - Job 20633: Subtask load_mysql_data
[2025-05-01T22:40:58.062+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-05-01T22:40:47+00:00 [running]> on host 486df48cccd2
[2025-05-01T22:40:58.405+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T22:40:47+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T22:40:47+00:00'
[2025-05-01T22:40:58.411+0000] {mymind_etl_dag.py:282} INFO - Iniciando carga a MySQL: 4 usuarios, 5 transcripciones.
[2025-05-01T22:40:58.412+0000] {mymind_etl_dag.py:293} INFO - Cargando 4 usuarios en la tabla users...
[2025-05-01T22:40:58.439+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-05-01T22:40:58.488+0000] {sql.py:547} INFO - Done loading. Loaded a total of 4 rows into users
[2025-05-01T22:40:58.488+0000] {mymind_etl_dag.py:301} INFO - Usuarios cargados exitosamente.
[2025-05-01T22:40:58.489+0000] {mymind_etl_dag.py:320} INFO - Cargando 5 transcripciones en la tabla transcriptions...
[2025-05-01T22:40:58.532+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-05-01T22:40:58.542+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into transcriptions
[2025-05-01T22:40:58.543+0000] {mymind_etl_dag.py:328} INFO - Transcripciones cargadas exitosamente.
[2025-05-01T22:40:58.544+0000] {mymind_etl_dag.py:333} INFO - Carga a MySQL completada con Ã©xito.
[2025-05-01T22:40:58.545+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-01T22:40:58.571+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250501T224047, start_date=20250501T224057, end_date=20250501T224058
[2025-05-01T22:40:58.624+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-01T22:40:58.689+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
