[2025-05-06T13:31:05.686+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.sync_and_load_mysql scheduled__2025-05-06T13:30:00+00:00 [queued]>
[2025-05-06T13:31:05.694+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.sync_and_load_mysql scheduled__2025-05-06T13:30:00+00:00 [queued]>
[2025-05-06T13:31:05.694+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-06T13:31:05.711+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): sync_and_load_mysql> on 2025-05-06 13:30:00+00:00
[2025-05-06T13:31:05.717+0000] {standard_task_runner.py:60} INFO - Started process 30834 to run task
[2025-05-06T13:31:05.720+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'sync_and_load_mysql', 'scheduled__2025-05-06T13:30:00+00:00', '--job-id', '34832', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmpthuclwas']
[2025-05-06T13:31:05.722+0000] {standard_task_runner.py:88} INFO - Job 34832: Subtask sync_and_load_mysql
[2025-05-06T13:31:05.771+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.sync_and_load_mysql scheduled__2025-05-06T13:30:00+00:00 [running]> on host 52beca4b988b
[2025-05-06T13:31:05.885+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='sync_and_load_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-06T13:30:00+00:00'
[2025-05-06T13:31:05.886+0000] {mymind_etl_dag.py:301} INFO - Iniciando sincronización y carga a MySQL: 6 usuarios, 8 transcripciones.
[2025-05-06T13:31:05.897+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-05-06T13:31:05.910+0000] {mymind_etl_dag.py:310} INFO - Obteniendo IDs actuales desde MySQL...
[2025-05-06T13:31:05.911+0000] {mymind_etl_dag.py:321} INFO - Usuarios a eliminar: 0
[2025-05-06T13:31:05.911+0000] {mymind_etl_dag.py:322} INFO - Transcripciones a eliminar: 0
[2025-05-06T13:31:05.911+0000] {mymind_etl_dag.py:355} INFO - Cargando 6 usuarios en la tabla users...
[2025-05-06T13:31:05.912+0000] {mymind_etl_dag.py:380} INFO - Usuarios cargados exitosamente.
[2025-05-06T13:31:05.913+0000] {mymind_etl_dag.py:393} INFO - Cargando 8 transcripciones en la tabla transcriptions...
[2025-05-06T13:31:05.915+0000] {mymind_etl_dag.py:423} INFO - Transcripciones cargadas exitosamente.
[2025-05-06T13:31:05.915+0000] {mymind_etl_dag.py:430} INFO - Sincronización y carga a MySQL completada con éxito.
[2025-05-06T13:31:05.916+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-06T13:31:05.927+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=sync_and_load_mysql, execution_date=20250506T133000, start_date=20250506T133105, end_date=20250506T133105
[2025-05-06T13:31:05.972+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-06T13:31:06.004+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
