[2025-05-05T18:41:05.118+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.sync_and_load_mysql scheduled__2025-05-05T18:40:00+00:00 [queued]>
[2025-05-05T18:41:05.126+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.sync_and_load_mysql scheduled__2025-05-05T18:40:00+00:00 [queued]>
[2025-05-05T18:41:05.127+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-05T18:41:05.143+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): sync_and_load_mysql> on 2025-05-05 18:40:00+00:00
[2025-05-05T18:41:05.148+0000] {standard_task_runner.py:60} INFO - Started process 9482 to run task
[2025-05-05T18:41:05.152+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'sync_and_load_mysql', 'scheduled__2025-05-05T18:40:00+00:00', '--job-id', '31456', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmpgvnvp5iz']
[2025-05-05T18:41:05.153+0000] {standard_task_runner.py:88} INFO - Job 31456: Subtask sync_and_load_mysql
[2025-05-05T18:41:05.212+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.sync_and_load_mysql scheduled__2025-05-05T18:40:00+00:00 [running]> on host f5b54f2720cb
[2025-05-05T18:41:05.318+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='sync_and_load_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T18:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-05T18:40:00+00:00'
[2025-05-05T18:41:05.319+0000] {mymind_etl_dag.py:301} INFO - Iniciando sincronización y carga a MySQL: 5 usuarios, 15 transcripciones.
[2025-05-05T18:41:05.330+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-05-05T18:41:05.340+0000] {mymind_etl_dag.py:310} INFO - Obteniendo IDs actuales desde MySQL...
[2025-05-05T18:41:05.341+0000] {mymind_etl_dag.py:321} INFO - Usuarios a eliminar: 0
[2025-05-05T18:41:05.341+0000] {mymind_etl_dag.py:322} INFO - Transcripciones a eliminar: 0
[2025-05-05T18:41:05.342+0000] {mymind_etl_dag.py:355} INFO - Cargando 5 usuarios en la tabla users...
[2025-05-05T18:41:05.343+0000] {mymind_etl_dag.py:380} INFO - Usuarios cargados exitosamente.
[2025-05-05T18:41:05.343+0000] {mymind_etl_dag.py:393} INFO - Cargando 15 transcripciones en la tabla transcriptions...
[2025-05-05T18:41:05.345+0000] {mymind_etl_dag.py:423} INFO - Transcripciones cargadas exitosamente.
[2025-05-05T18:41:05.346+0000] {mymind_etl_dag.py:430} INFO - Sincronización y carga a MySQL completada con éxito.
[2025-05-05T18:41:05.346+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-05T18:41:05.357+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=sync_and_load_mysql, execution_date=20250505T184000, start_date=20250505T184105, end_date=20250505T184105
[2025-05-05T18:41:05.403+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-05T18:41:05.429+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
