[2025-05-01T22:40:51.513+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-05-01T22:40:39+00:00 [queued]>
[2025-05-01T22:40:51.566+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-05-01T22:40:39+00:00 [queued]>
[2025-05-01T22:40:51.566+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-01T22:40:51.603+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-05-01 22:40:39+00:00
[2025-05-01T22:40:51.613+0000] {standard_task_runner.py:60} INFO - Started process 239 to run task
[2025-05-01T22:40:51.638+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-05-01T22:40:39+00:00', '--job-id', '20601', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmp7dou_h3g']
[2025-05-01T22:40:51.645+0000] {standard_task_runner.py:88} INFO - Job 20601: Subtask load_mysql_data
[2025-05-01T22:40:51.830+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-05-01T22:40:39+00:00 [running]> on host 486df48cccd2
[2025-05-01T22:40:52.246+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T22:40:39+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T22:40:39+00:00'
[2025-05-01T22:40:52.249+0000] {mymind_etl_dag.py:282} INFO - Iniciando carga a MySQL: 4 usuarios, 5 transcripciones.
[2025-05-01T22:40:52.250+0000] {mymind_etl_dag.py:293} INFO - Cargando 4 usuarios en la tabla users...
[2025-05-01T22:40:52.281+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-05-01T22:40:52.325+0000] {sql.py:547} INFO - Done loading. Loaded a total of 4 rows into users
[2025-05-01T22:40:52.326+0000] {mymind_etl_dag.py:301} INFO - Usuarios cargados exitosamente.
[2025-05-01T22:40:52.326+0000] {mymind_etl_dag.py:320} INFO - Cargando 5 transcripciones en la tabla transcriptions...
[2025-05-01T22:40:52.380+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-05-01T22:40:52.409+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into transcriptions
[2025-05-01T22:40:52.411+0000] {mymind_etl_dag.py:328} INFO - Transcripciones cargadas exitosamente.
[2025-05-01T22:40:52.413+0000] {mymind_etl_dag.py:333} INFO - Carga a MySQL completada con Ã©xito.
[2025-05-01T22:40:52.419+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-01T22:40:52.465+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250501T224039, start_date=20250501T224051, end_date=20250501T224052
[2025-05-01T22:40:52.570+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-01T22:40:52.639+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
