[2025-04-25T14:05:04.003+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-25T14:00:00+00:00 [queued]>
[2025-04-25T14:05:04.012+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-25T14:00:00+00:00 [queued]>
[2025-04-25T14:05:04.012+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-25T14:05:04.028+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-25 14:00:00+00:00
[2025-04-25T14:05:04.033+0000] {standard_task_runner.py:60} INFO - Started process 50272 to run task
[2025-04-25T14:05:04.036+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-25T14:00:00+00:00', '--job-id', '1742', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmpy0d4c3ha']
[2025-04-25T14:05:04.038+0000] {standard_task_runner.py:88} INFO - Job 1742: Subtask load_mysql_data
[2025-04-25T14:05:04.097+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-25T14:00:00+00:00 [running]> on host 64c6827685b2
[2025-04-25T14:05:04.224+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-25T14:00:00+00:00'
[2025-04-25T14:05:04.226+0000] {mymind_etl_dag.py:284} INFO - Iniciando carga a MySQL: 3 usuarios, 5 transcripciones.
[2025-04-25T14:05:04.226+0000] {mymind_etl_dag.py:295} INFO - Cargando 3 usuarios en la tabla users...
[2025-04-25T14:05:04.237+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-25T14:05:04.254+0000] {sql.py:547} INFO - Done loading. Loaded a total of 3 rows into users
[2025-04-25T14:05:04.255+0000] {mymind_etl_dag.py:303} INFO - Usuarios cargados exitosamente.
[2025-04-25T14:05:04.255+0000] {mymind_etl_dag.py:322} INFO - Cargando 5 transcripciones en la tabla transcriptions...
[2025-04-25T14:05:04.263+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-25T14:05:04.269+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into transcriptions
[2025-04-25T14:05:04.270+0000] {mymind_etl_dag.py:330} INFO - Transcripciones cargadas exitosamente.
[2025-04-25T14:05:04.270+0000] {mymind_etl_dag.py:335} INFO - Carga a MySQL completada con Ã©xito.
[2025-04-25T14:05:04.270+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-25T14:05:04.281+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250425T140000, start_date=20250425T140504, end_date=20250425T140504
[2025-04-25T14:05:04.328+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-25T14:05:04.360+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
