[2025-04-29T23:00:20.528+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T23:00:14+00:00 [queued]>
[2025-04-29T23:00:20.539+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T23:00:14+00:00 [queued]>
[2025-04-29T23:00:20.539+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-29T23:00:20.554+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-29 23:00:14+00:00
[2025-04-29T23:00:20.560+0000] {standard_task_runner.py:60} INFO - Started process 10063 to run task
[2025-04-29T23:00:20.564+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-29T23:00:14+00:00', '--job-id', '20431', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmpudz4j4ld']
[2025-04-29T23:00:20.566+0000] {standard_task_runner.py:88} INFO - Job 20431: Subtask load_mysql_data
[2025-04-29T23:00:20.629+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T23:00:14+00:00 [running]> on host d10170178d9f
[2025-04-29T23:00:20.763+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T23:00:14+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-29T23:00:14+00:00'
[2025-04-29T23:00:20.764+0000] {mymind_etl_dag.py:284} INFO - Iniciando carga a MySQL: 5 usuarios, 13 transcripciones.
[2025-04-29T23:00:20.765+0000] {mymind_etl_dag.py:295} INFO - Cargando 5 usuarios en la tabla users...
[2025-04-29T23:00:20.778+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T23:00:20.798+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into users
[2025-04-29T23:00:20.798+0000] {mymind_etl_dag.py:303} INFO - Usuarios cargados exitosamente.
[2025-04-29T23:00:20.800+0000] {mymind_etl_dag.py:322} INFO - Cargando 13 transcripciones en la tabla transcriptions...
[2025-04-29T23:00:20.811+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T23:00:20.829+0000] {sql.py:547} INFO - Done loading. Loaded a total of 13 rows into transcriptions
[2025-04-29T23:00:20.831+0000] {mymind_etl_dag.py:330} INFO - Transcripciones cargadas exitosamente.
[2025-04-29T23:00:20.831+0000] {mymind_etl_dag.py:335} INFO - Carga a MySQL completada con Ã©xito.
[2025-04-29T23:00:20.832+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-29T23:00:20.851+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250429T230014, start_date=20250429T230020, end_date=20250429T230020
[2025-04-29T23:00:20.900+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-29T23:00:20.921+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
