[2025-04-29T08:41:01.853+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T08:40:55+00:00 [queued]>
[2025-04-29T08:41:01.863+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T08:40:55+00:00 [queued]>
[2025-04-29T08:41:01.864+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-29T08:41:01.876+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-29 08:40:55+00:00
[2025-04-29T08:41:01.882+0000] {standard_task_runner.py:60} INFO - Started process 50513 to run task
[2025-04-29T08:41:01.886+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-29T08:40:55+00:00', '--job-id', '12863', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmp6mjtlgbu']
[2025-04-29T08:41:01.887+0000] {standard_task_runner.py:88} INFO - Job 12863: Subtask load_mysql_data
[2025-04-29T08:41:01.947+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-29T08:40:55+00:00 [running]> on host 9c429c713f45
[2025-04-29T08:41:02.053+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T08:40:55+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-29T08:40:55+00:00'
[2025-04-29T08:41:02.054+0000] {mymind_etl_dag.py:284} INFO - Iniciando carga a MySQL: 5 usuarios, 9 transcripciones.
[2025-04-29T08:41:02.055+0000] {mymind_etl_dag.py:295} INFO - Cargando 5 usuarios en la tabla users...
[2025-04-29T08:41:02.064+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T08:41:02.076+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into users
[2025-04-29T08:41:02.076+0000] {mymind_etl_dag.py:303} INFO - Usuarios cargados exitosamente.
[2025-04-29T08:41:02.077+0000] {mymind_etl_dag.py:322} INFO - Cargando 9 transcripciones en la tabla transcriptions...
[2025-04-29T08:41:02.083+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-29T08:41:02.088+0000] {sql.py:547} INFO - Done loading. Loaded a total of 9 rows into transcriptions
[2025-04-29T08:41:02.089+0000] {mymind_etl_dag.py:330} INFO - Transcripciones cargadas exitosamente.
[2025-04-29T08:41:02.089+0000] {mymind_etl_dag.py:335} INFO - Carga a MySQL completada con Ã©xito.
[2025-04-29T08:41:02.089+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-29T08:41:02.097+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250429T084055, start_date=20250429T084101, end_date=20250429T084102
[2025-04-29T08:41:02.137+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-29T08:41:02.160+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
