[2025-04-28T22:00:24.840+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-28T22:00:17+00:00 [queued]>
[2025-04-28T22:00:24.853+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-28T22:00:17+00:00 [queued]>
[2025-04-28T22:00:24.854+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-28T22:00:24.876+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_mysql_data> on 2025-04-28 22:00:17+00:00
[2025-04-28T22:00:24.884+0000] {standard_task_runner.py:60} INFO - Started process 15710 to run task
[2025-04-28T22:00:24.888+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mymind_mongo_to_mysql_etl', 'load_mysql_data', 'scheduled__2025-04-28T22:00:17+00:00', '--job-id', '7023', '--raw', '--subdir', 'DAGS_FOLDER/mymind_etl_dag.py', '--cfg-path', '/tmp/tmp_9nmzys0']
[2025-04-28T22:00:24.890+0000] {standard_task_runner.py:88} INFO - Job 7023: Subtask load_mysql_data
[2025-04-28T22:00:24.955+0000] {task_command.py:423} INFO - Running <TaskInstance: mymind_mongo_to_mysql_etl.load_mysql_data scheduled__2025-04-28T22:00:17+00:00 [running]> on host 9c429c713f45
[2025-04-28T22:00:25.085+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mymind_mongo_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_mysql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T22:00:17+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T22:00:17+00:00'
[2025-04-28T22:00:25.086+0000] {mymind_etl_dag.py:284} INFO - Iniciando carga a MySQL: 5 usuarios, 9 transcripciones.
[2025-04-28T22:00:25.086+0000] {mymind_etl_dag.py:295} INFO - Cargando 5 usuarios en la tabla users...
[2025-04-28T22:00:25.096+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-28T22:00:25.108+0000] {sql.py:547} INFO - Done loading. Loaded a total of 5 rows into users
[2025-04-28T22:00:25.109+0000] {mymind_etl_dag.py:303} INFO - Usuarios cargados exitosamente.
[2025-04-28T22:00:25.109+0000] {mymind_etl_dag.py:322} INFO - Cargando 9 transcripciones en la tabla transcriptions...
[2025-04-28T22:00:25.117+0000] {base.py:83} INFO - Using connection ID 'mysql_mymind_dw' for task execution.
[2025-04-28T22:00:25.122+0000] {sql.py:547} INFO - Done loading. Loaded a total of 9 rows into transcriptions
[2025-04-28T22:00:25.123+0000] {mymind_etl_dag.py:330} INFO - Transcripciones cargadas exitosamente.
[2025-04-28T22:00:25.123+0000] {mymind_etl_dag.py:335} INFO - Carga a MySQL completada con Ã©xito.
[2025-04-28T22:00:25.123+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-28T22:00:25.133+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mymind_mongo_to_mysql_etl, task_id=load_mysql_data, execution_date=20250428T220017, start_date=20250428T220024, end_date=20250428T220025
[2025-04-28T22:00:25.181+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T22:00:25.206+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
